#!/usr/bin/env bash
# SessionStart hook: detect runtime environment, install dependencies, and
# write an environment config file so export scripts know which backends
# are available (Typst vs Python-fallback for PDF, uv vs pip, etc.).
#
# Exit codes:
#   0 — success (all critical dependencies installed or available)
#   1 — critical failure (no package manager available)
# Non-critical issues (missing optional fonts, etc.) emit warnings only.
# Re-detects on every session start to handle Cowork VM updates.

set -uo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_DIR="${PLUGIN_ROOT}"
CONFIG_FILE="${CONFIG_DIR}/.env-config"
FONTS_DIR="${PLUGIN_ROOT}/fonts"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log_info()  { echo "setup-deps: $*"; }
log_warn()  { echo "WARNING: $*" >&2; }
log_error() { echo "ERROR: $*" >&2; }

# ---------------------------------------------------------------------------
# 1. Detect package manager (uv vs pip)
# ---------------------------------------------------------------------------

HAS_UV=false
HAS_PIP=false
PKG_MANAGER="none"

if command -v uv &>/dev/null; then
  HAS_UV=true
  PKG_MANAGER="uv"
elif command -v pip &>/dev/null || command -v pip3 &>/dev/null; then
  HAS_PIP=true
  if command -v pip3 &>/dev/null; then
    PKG_MANAGER="pip3"
  else
    PKG_MANAGER="pip"
  fi
fi

# ---------------------------------------------------------------------------
# 2. Install / sync dependencies
# ---------------------------------------------------------------------------

# Track per-package install status for reporting.
HAS_PYTHON_DOCX=false
HAS_PDF_FALLBACK=false
FAILED_PACKAGES=""

# Helper: map pip package name to Python import name (bash 3.2 compatible).
import_name_for() {
  case "$1" in
    pymupdf)     echo "fitz" ;;
    jsonschema)  echo "jsonschema" ;;
    python-docx) echo "docx" ;;
    fpdf2)       echo "fpdf" ;;
    *)           echo "$1" ;;
  esac
}

if $HAS_UV; then
  cd "$PLUGIN_ROOT"
  if uv sync --quiet 2>/dev/null; then
    # uv sync installs everything in pyproject.toml -- verify key packages.
    if uv run --quiet python -c "import docx" 2>/dev/null; then
      HAS_PYTHON_DOCX=true
    fi
    if uv run --quiet python -c "import fpdf" 2>/dev/null; then
      HAS_PDF_FALLBACK=true
    fi
  else
    log_warn "Failed to sync dependencies via uv in $PLUGIN_ROOT."
    log_warn "Some features may not work. Try running 'uv sync' manually."
  fi

elif $HAS_PIP; then
  log_info "uv not found; using $PKG_MANAGER to check dependencies."
  # In pip/Cowork environments, only install missing packages.
  for pkg in pymupdf jsonschema python-docx fpdf2; do
    import_name=$(import_name_for "$pkg")
    if python3 -c "import ${import_name}" 2>/dev/null; then
      log_info "$pkg already installed (verified via 'import ${import_name}')."
    else
      log_info "Installing $pkg via $PKG_MANAGER..."
      if $PKG_MANAGER install --quiet "$pkg" 2>/dev/null; then
        log_info "$pkg installed successfully."
      else
        log_warn "Failed to install $pkg via $PKG_MANAGER."
        log_warn "If network is unavailable, install manually: $PKG_MANAGER install $pkg"
        FAILED_PACKAGES="${FAILED_PACKAGES} ${pkg}"
      fi
    fi
  done

  # Verify key packages after install attempts.
  if python3 -c "import docx" 2>/dev/null; then
    HAS_PYTHON_DOCX=true
  fi
  if python3 -c "import fpdf" 2>/dev/null; then
    HAS_PDF_FALLBACK=true
  fi

else
  log_error "Neither 'uv' nor 'pip' is available."
  log_error "Cannot install required dependencies. Export features will not work."
  log_error ""
  log_error "To fix, install one of the following:"
  log_error "  uv:  curl -LsSf https://astral.sh/uv/install.sh | sh"
  log_error "       https://docs.astral.sh/uv/getting-started/installation/"
  log_error "  pip: https://pip.pypa.io/en/stable/installation/"
  log_error ""
  log_error "Then re-run the session to trigger dependency installation."

  # Write a minimal config so scripts can detect the broken state.
  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_FILE" <<EOF
# Auto-generated by hooks/setup-deps.sh -- do not edit manually.
# CRITICAL: No package manager was found. Export features are disabled.
HAS_UV=false
HAS_PIP=false
PKG_MANAGER=none
HAS_TYPST=false
TYPST_SOURCE=none
PDF_BACKEND=none
HAS_PYTHON_DOCX=false
HAS_PDF_FALLBACK=false
FONTS_DIR=${FONTS_DIR}
FONTS_ACCESSIBLE=false
PLUGIN_ROOT=${PLUGIN_ROOT}
EOF
  exit 1
fi

# Report failed packages if any.
if [ -n "$FAILED_PACKAGES" ]; then
  log_warn "The following packages could not be installed:${FAILED_PACKAGES}"
  log_warn "These packages need manual installation when network is available:"
  for pkg in $FAILED_PACKAGES; do
    log_warn "  $PKG_MANAGER install $pkg"
  done
fi

# ---------------------------------------------------------------------------
# 3. Detect Typst availability
# ---------------------------------------------------------------------------

HAS_TYPST=false
TYPST_SOURCE="none"

# Check for the Typst CLI binary first (fastest PDF compilation).
if command -v typst &>/dev/null; then
  HAS_TYPST=true
  TYPST_SOURCE="cli"
fi

# Check for the Python typst package (used by md-to-pdf.py via `import typst`).
if ! $HAS_TYPST; then
  if python3 -c "import typst" 2>/dev/null; then
    HAS_TYPST=true
    TYPST_SOURCE="python"
  elif $HAS_UV; then
    # uv sync may have installed it in a venv -- check via uv run.
    if uv run --quiet --directory "$PLUGIN_ROOT" python -c "import typst" 2>/dev/null; then
      HAS_TYPST=true
      TYPST_SOURCE="python-uv"
    fi
  fi
fi

# Determine PDF backend
if $HAS_TYPST; then
  PDF_BACKEND="typst"
else
  PDF_BACKEND="python-fallback"
  log_warn "Typst is not available. PDF export will use the Python fallback renderer."
fi

# ---------------------------------------------------------------------------
# 4. Check bundled fonts directory
# ---------------------------------------------------------------------------

FONTS_ACCESSIBLE=false

if [ -d "$FONTS_DIR" ]; then
  # Check that at least one TTF/OTF file exists.
  font_count=$(find "$FONTS_DIR" -maxdepth 1 \( -name "*.ttf" -o -name "*.otf" \) 2>/dev/null | wc -l | tr -d ' ')
  if [ "$font_count" -gt 0 ]; then
    FONTS_ACCESSIBLE=true
    log_info "Bundled fonts directory found: $FONTS_DIR ($font_count font files)"
  else
    log_warn "Fonts directory exists but contains no TTF/OTF files: $FONTS_DIR"
  fi
else
  log_warn "Bundled fonts directory not found: $FONTS_DIR"
  log_warn "PDF export with custom fonts may not work correctly."
fi

# ---------------------------------------------------------------------------
# 5. Resolve workspace root
# ---------------------------------------------------------------------------

# Override with RESUME_WORKSPACE env var; otherwise default to plugin workspace.
if [ -n "${RESUME_WORKSPACE:-}" ]; then
  WORKSPACE_ROOT="$RESUME_WORKSPACE"
else
  WORKSPACE_ROOT="${PLUGIN_ROOT}/workspace"
fi

# ---------------------------------------------------------------------------
# 6. Write environment config file
# ---------------------------------------------------------------------------

cat > "$CONFIG_FILE" <<EOF
# Auto-generated by hooks/setup-deps.sh -- do not edit manually.
# Re-generated on every session start.
HAS_UV=${HAS_UV}
HAS_PIP=${HAS_PIP}
PKG_MANAGER=${PKG_MANAGER}
HAS_TYPST=${HAS_TYPST}
TYPST_SOURCE=${TYPST_SOURCE}
PDF_BACKEND=${PDF_BACKEND}
HAS_PYTHON_DOCX=${HAS_PYTHON_DOCX}
HAS_PDF_FALLBACK=${HAS_PDF_FALLBACK}
FONTS_DIR=${FONTS_DIR}
FONTS_ACCESSIBLE=${FONTS_ACCESSIBLE}
PLUGIN_ROOT=${PLUGIN_ROOT}
# Workspace root for resume data (input/output).
# Override with RESUME_WORKSPACE env var or --workspace CLI argument.
WORKSPACE_ROOT=${WORKSPACE_ROOT}
EOF

# Clean up legacy config location if it exists.
OLD_CONFIG="${PLUGIN_ROOT}/workspace/.env-config"
if [ -f "$OLD_CONFIG" ]; then
  rm -f "$OLD_CONFIG"
  log_info "Removed legacy config file at workspace/.env-config"
fi

log_info "Environment detected: pkg_manager=${PKG_MANAGER}, pdf_backend=${PDF_BACKEND}, typst_source=${TYPST_SOURCE}"
log_info "  python-docx=${HAS_PYTHON_DOCX}, pdf_fallback=${HAS_PDF_FALLBACK}, fonts=${FONTS_ACCESSIBLE}"
log_info "  workspace_root=${WORKSPACE_ROOT}"
