"""Environment-aware PDF routing: Typst or Python fallback.

Automatically selects the best available PDF backend based on the
environment config generated by ``hooks/setup-deps.sh``.  When Typst is
available (Claude Code), it delegates to ``md-to-pdf.py``.  When Typst
is unavailable (Cowork VM), it delegates to ``md_to_pdf_fallback.py``.
If Typst exists but fails at runtime, it catches the error and falls
back to the Python renderer with a warning.

Usage as CLI (drop-in replacement for md-to-pdf.py):
    uv run scripts/md_to_pdf_router.py <input.md> [output.pdf] [--preset PRESET] ...

Usage as module:
    from md_to_pdf_router import generate_pdf_routed, detect_pdf_backend

    backend = detect_pdf_backend()
    generate_pdf_routed(md_text, output_path, preset="modern")
"""

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent


def _extract_install_cmd(dep_message: str | None) -> str:
    """Extract the install command from a dependency check message."""
    if dep_message is None:
        return "(already installed)"
    for line in dep_message.split("\n"):
        stripped = line.strip()
        if stripped.startswith("uv ") or stripped.startswith("pip"):
            return stripped
    return "see dependency check output above"


def detect_pdf_backend(config: dict[str, str] | None = None) -> str:
    """Detect which PDF backend to use.

    Returns one of: ``'typst'``, ``'python-fallback'``, or ``'none'``.

    Resolution order:
    1. If *config* is provided, use its ``PDF_BACKEND`` value.
    2. Otherwise load from ``.env-config`` via ``env_config``.
    3. If the config file is missing (first run before setup hook),
       attempt a live Typst import probe as a fallback.

    Parameters
    ----------
    config:
        Pre-loaded environment config dict (for testing). If ``None``,
        ``env_config.load_env_config()`` is called.
    """
    from env_config import load_env_config

    cfg = config or load_env_config()

    backend = cfg.get("PDF_BACKEND", "python-fallback")

    # If config file was never written (all defaults), do a live probe
    config_path = PROJECT_ROOT / ".env-config"
    if not config_path.exists() and config is None:
        backend = _probe_typst_live()

    return backend


def _probe_typst_live() -> str:
    """Probe for Typst availability without a config file.

    Called when ``.env-config`` does not exist (e.g. first run
    before the SessionStart hook fires).
    """
    try:
        import typst  # noqa: F401
        return "typst"
    except ImportError:
        pass

    # Check if fpdf2 is available
    try:
        from fpdf import FPDF  # noqa: F401
        return "python-fallback"
    except ImportError:
        pass

    return "none"


def generate_pdf_routed(
    md_text: str,
    output_path: str,
    *,
    preset: str = "modern",
    font: str | None = None,
    color: str | None = None,
    margin: str | None = None,
    page_size: str = "letter",
    line_spacing: str | None = None,
    section_spacing: str | None = None,
    pdf_a: bool = False,
    config: dict[str, str] | None = None,
) -> Path:
    """Generate a PDF from resume markdown, routing to the best backend.

    Parameters
    ----------
    md_text:
        Raw markdown text of the resume.
    output_path:
        Destination file path for the PDF.
    preset:
        Style preset name (modern, classic, compact, harvard).
    font:
        Font family override.
    color:
        Accent colour (#RRGGBB or named preset).
    margin:
        Margin preset (narrow, standard, wide).
    page_size:
        Page size (letter, a4).
    line_spacing:
        Line spacing preset (tight, standard, relaxed).
    section_spacing:
        Section spacing preset (compact, standard, generous).
    pdf_a:
        Enable PDF/A-2b compliance (Typst only; ignored by fallback).
    config:
        Pre-loaded environment config dict (for testing).

    Returns
    -------
    Path
        The path to the generated PDF file.

    Raises
    ------
    RuntimeError
        If neither Typst nor the Python fallback is available.
    """
    from parse_resume import parse_resume_markdown

    backend = detect_pdf_backend(config)

    if backend == "none":
        from export_edge_cases import check_dependency_available
        # Provide environment-specific install instructions
        typst_msg = check_dependency_available("typst", "typst")
        fpdf_msg = check_dependency_available("fpdf2", "fpdf")
        raise RuntimeError(
            "No PDF backend is available. Install one of the following:\n\n"
            "Option 1 (Typst - higher quality):\n"
            f"  {_extract_install_cmd(typst_msg)}\n\n"
            "Option 2 (fpdf2 - pure Python, works everywhere):\n"
            f"  {_extract_install_cmd(fpdf_msg)}\n\n"
            "After installing, re-run the export command.\n"
            "Alternatively, run 'uv sync' or the session setup hook to install all dependencies."
        )

    parsed = parse_resume_markdown(md_text)
    warnings = parsed.get("warnings", [])
    for w in warnings:
        print(f"WARNING: {w}", file=sys.stderr)

    if backend == "typst":
        return _generate_via_typst(
            parsed,
            output_path,
            preset=preset,
            font=font,
            color=color,
            margin=margin,
            page_size=page_size,
            line_spacing=line_spacing,
            section_spacing=section_spacing,
            pdf_a=pdf_a,
        )

    # python-fallback
    return _generate_via_fallback(
        parsed,
        output_path,
        preset=preset,
        font=font,
        color=color,
        margin=margin,
        page_size=page_size,
        line_spacing=line_spacing,
        section_spacing=section_spacing,
    )


def _generate_via_typst(
    parsed: dict,
    output_path: str,
    *,
    preset: str,
    font: str | None,
    color: str | None,
    margin: str | None,
    page_size: str,
    line_spacing: str | None,
    section_spacing: str | None,
    pdf_a: bool,
) -> Path:
    """Attempt PDF generation via the Typst pipeline.

    If Typst fails at runtime (e.g. binary exists but crashes), catch
    the error and fall back to the Python renderer with a warning.
    """
    try:
        # Import the Typst-based module
        sys.path.insert(0, str(SCRIPT_DIR))
        import importlib.util

        spec = importlib.util.spec_from_file_location(
            "md_to_pdf", SCRIPT_DIR / "md-to-pdf.py"
        )
        md_to_pdf = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(md_to_pdf)

        # Build config dict matching what md-to-pdf.py expects
        config = {
            "preset": preset,
            "font": font,
            "color": color,
            "margin": margin,
            "page_size": page_size,
            "line_spacing": line_spacing,
            "section_spacing": section_spacing,
            "pdf_a": pdf_a,
            "output": output_path,
        }

        config = md_to_pdf.resolve_config(config)
        if "error" in config:
            raise ValueError(config["error"])

        typst_content = md_to_pdf.generate_typst_content(parsed)

        template_path = md_to_pdf.TEMPLATES_DIR / f"{preset}.typ"
        if not template_path.exists():
            raise FileNotFoundError(f"Template not found: {template_path}")

        sys_inputs = md_to_pdf.build_sys_inputs(config)
        md_to_pdf.generate_pdf(
            typst_content,
            template_path,
            sys_inputs,
            output_path,
            pdf_a=pdf_a,
            name=parsed.get("name", ""),
        )

        return Path(output_path)

    except Exception as exc:
        # Typst failed at runtime -- fall back to Python with warning
        print(
            f"WARNING: Typst PDF generation failed: {exc}. "
            f"Falling back to Python PDF renderer.",
            file=sys.stderr,
        )
        return _generate_via_fallback(
            parsed,
            output_path,
            preset=preset,
            font=font,
            color=color,
            margin=margin,
            page_size=page_size,
            line_spacing=line_spacing,
            section_spacing=section_spacing,
        )


def _generate_via_fallback(
    parsed: dict,
    output_path: str,
    *,
    preset: str,
    font: str | None,
    color: str | None,
    margin: str | None,
    page_size: str,
    line_spacing: str | None,
    section_spacing: str | None,
) -> Path:
    """Generate PDF via the Python (fpdf2) fallback renderer."""
    from md_to_pdf_fallback import generate_pdf_fallback

    return generate_pdf_fallback(
        parsed,
        output_path,
        preset=preset,
        font=font,
        color=color,
        margin=margin,
        page_size=page_size,
        line_spacing=line_spacing,
        section_spacing=section_spacing,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_cli_args(argv: list[str]) -> dict:
    """Parse CLI arguments into a config dict.

    Accepts the same options as both ``md-to-pdf.py`` and
    ``md_to_pdf_fallback.py``.
    """
    if len(argv) < 2:
        return {"error": "Missing input file argument"}

    config: dict = {
        "input": argv[1],
        "output": None,
        "preset": "modern",
        "font": None,
        "color": None,
        "margin": None,
        "page_size": "letter",
        "line_spacing": None,
        "section_spacing": None,
        "pdf_a": False,
    }

    i = 2
    while i < len(argv):
        arg = argv[i]
        if arg == "--preset" and i + 1 < len(argv):
            config["preset"] = argv[i + 1].lower()
            i += 2
        elif arg == "--font" and i + 1 < len(argv):
            config["font"] = argv[i + 1]
            i += 2
        elif arg == "--color" and i + 1 < len(argv):
            config["color"] = argv[i + 1]
            i += 2
        elif arg == "--margin" and i + 1 < len(argv):
            config["margin"] = argv[i + 1].lower()
            i += 2
        elif arg == "--page-size" and i + 1 < len(argv):
            config["page_size"] = argv[i + 1].lower()
            i += 2
        elif arg == "--line-spacing" and i + 1 < len(argv):
            config["line_spacing"] = argv[i + 1].lower()
            i += 2
        elif arg == "--section-spacing" and i + 1 < len(argv):
            config["section_spacing"] = argv[i + 1].lower()
            i += 2
        elif arg == "--pdf-a":
            config["pdf_a"] = True
            i += 1
        elif not arg.startswith("--") and config["output"] is None:
            config["output"] = arg
            i += 1
        else:
            return {"error": f"Unknown argument: {arg}"}

    return config


def main() -> int:
    config = parse_cli_args(sys.argv)
    if "error" in config:
        print(f"Error: {config['error']}", file=sys.stderr)
        print(
            f"Usage: {sys.argv[0]} <input.md> [output.pdf] [--preset PRESET] "
            "[--font FONT] [--color COLOR] [--margin MARGIN] "
            "[--page-size SIZE] [--line-spacing SPACING] "
            "[--section-spacing SPACE] [--pdf-a]",
            file=sys.stderr,
        )
        return 1

    input_path = Path(config["input"])

    # Validate source file with actionable error message
    from export_edge_cases import check_source_file, check_output_size, check_page_count_pdf, emit_warnings
    source_error = check_source_file(input_path)
    if source_error:
        print(f"Error: {source_error}", file=sys.stderr)
        return 1

    try:
        md_text = input_path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
        print(f"Error: File is not valid text/markdown: {exc}", file=sys.stderr)
        return 1

    if not md_text.strip():
        print("Error: Input file is empty", file=sys.stderr)
        return 1

    output_path = config.get("output") or str(
        input_path.with_name(f"{input_path.stem}-optimized.pdf")
    )

    try:
        result_path = generate_pdf_routed(
            md_text,
            output_path,
            preset=config["preset"],
            font=config.get("font"),
            color=config.get("color"),
            margin=config.get("margin"),
            page_size=config.get("page_size", "letter"),
            line_spacing=config.get("line_spacing"),
            section_spacing=config.get("section_spacing"),
            pdf_a=config.get("pdf_a", False),
        )
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    except (ImportError, FileNotFoundError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    # Post-generation edge case checks
    size_warnings = check_output_size(result_path)
    page_warnings = check_page_count_pdf(result_path)
    all_warnings = size_warnings + page_warnings
    if all_warnings:
        emit_warnings(all_warnings)

    file_size = result_path.stat().st_size
    if file_size < 1024 * 1024:
        size_str = f"{file_size / 1024:.1f} KB"
    else:
        size_str = f"{file_size / (1024 * 1024):.1f} MB"

    backend = detect_pdf_backend()
    print(f"PDF generated: {result_path} ({size_str}) [backend: {backend}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
